# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bgremover.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'bgremover.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62gremover.proto\x12\x02pb\"\x1d\n\x0cImageRequest\x12\r\n\x05Image\x18\x01 \x01(\x0c\"\'\n\rImageResponse\x12\x16\n\x0eProcessedImage\x18\x01 \x01(\x0c\x32=\n\x06Remove\x12\x33\n\x08RemoveBG\x12\x10.pb.ImageRequest\x1a\x11.pb.ImageResponse\"\x00(\x01\x42\x07Z\x05../pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bgremover_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005../pb'
  _globals['_IMAGEREQUEST']._serialized_start=23
  _globals['_IMAGEREQUEST']._serialized_end=52
  _globals['_IMAGERESPONSE']._serialized_start=54
  _globals['_IMAGERESPONSE']._serialized_end=93
  _globals['_REMOVE']._serialized_start=95
  _globals['_REMOVE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
