name: Client side deployment


on:
  push:
    branches:
      - master
    paths:
      - http/client/**

    tags:
      - client*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Client Build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
    

      - name: Cache clean npm
        run: |
          cd http/client
          npm cache clean --force
          
      - name: Install dependencies
        run: |
          cd http/client
          npm ci --force

      - name: Build
        run: | 
          cd http/client
          npm run build
        env:
          CI: false

      - name: Copy build folder
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.USER }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: http/client/build/
          target: /home/web-apps/bgremover
          
